# Create config.toml and use the stanza below as an example.

# Recommended to keep these values since calling the APIs too fast will exceed the Meraki API rate limits.
[general]
thread = 4

[requests]
sleep_min = 1.0
sleep_max = 1.5

# Due to security reasons, this app does NOT create an HEC input.
# Create the input manually and make sure both index=meraki and index=main are allowed.
# Change the HEC settings below for your input.
[hec]
url = "https://localhost:8088/services/collector/event"
  [hec.headers]
  Authorization = "Splunk xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

[meraki_api]
# This app already creates an index called meraki_api.
index = "meraki_api"
# List all orgs by running "./meraki_get_data.py --org" after setting the Meraki API key below.
# Enter only the orgs you want data from.
orgs = [
    11111,
    22222,
]
# Regex to filter on network tags.
# The regex must match the entire tag string.
# Tags that doesn't match with any regex will be excluded.
# Set the list empty [] to disable any filtering.
network_tag_regexes = [
    "FOOBAR.+", # This regex will match on networks with tags that start with FOOBAR.
    "^$", # This regex will match on networks without tags.
]
# This value correspond to the interval of inputs.conf for [script://./bin/meraki_get_data.sh], ie every hour is repeat=3600.
repeat = 3600
  [meraki_api.headers]
  X-Cisco-Meraki-API-Key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
